personalweb/project/models.py
from personalweb import db

class Project(db.Model):
  __tablename__ = 'projects'
  
  id = db.Column(db.Integer, primary_key = True)
  title = db.Column(db.String(60))
  description = db.Column(db.Text)
  
  def __init__(self, title, description):
    self.title = title
    self.description = description 
    
  def __repr__(self):
    return f'Project: {self.title}'
    

personalweb/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy 

app = Flask(__name__)

app.config.from_object('config.ProductionConfig')
db = SQLAlchemy(app) # conect db

from flask_bootstrap import Bootstrap
from personalweb.views import bp
from personalweb.project.views import project

bootstrap = Bootstrap(app)
app.register_blueprint(bp)
app.register_blueprint(project)

# Execute all cons
db.create_all()

personalweb/project/views.py
from crypt import methods
from flask import render_template, Blueprint, request, redirect, url_for, flash
from personalweb.project.models import Project
from personalweb import db

project = Blueprint('project', __name__)

@project.route('/projects')
@project.route('/projects/index')
def show_projects():
  projects = Project.query.all()
  db.session.commit()
  return render_template('project/index.html', projects = projects)

@project.route('/projects/create')
def create():
  return render_template('/project/create.html')

@project.route('/projects/insert', methods=['POST'])
def insert():
  # retrieve form data
  title = request.form.get('title')
  description = request.form.get('description')
  
  # save data in a objetc
  project = Project(title, description)
  
  # send data to db
  db.session.add(project)
  db.session.commit()
  
  flash('Project added')
  
  # redirect home page
  return redirect(url_for('project.show_projects'))

@project.route('/projects/edit/<int:id>')
def edit(id):
  project = Project.query.get_or_404(id)
  return render_template('project/edit.html', project = project)

@project.route('/projects/update/<int:id>', methods=['POST'])
def update(id):
  project = Project.query.get_or_404(id)
  project.title = request.form.get('title')
  project.description = request.form.get('description')
  
  db.session.add(project)
  db.session.commit()
  flash('Project edited')
  return redirect(url_for('project.show_projects'))

@project.route('/projects/delete/<int:id>')
def delete(id):
  project = Project.query.get_or_404(id)
  
  db.session.delete(project)
  db.session.commit()
  flash('Project deleted')
  return redirect(url_for('project.show_projects'))

personalweb/views.py
# from personalweb import app
from flask import render_template, Blueprint

bp = Blueprint('bp', __name__)

@bp.route('/')
@bp.route('/home')
def home():
  return render_template('home.html')

@bp.route('/portfolio')
def portfolio():
  return render_template('portfolio.html')

@bp.route('/contact')
def contact():
  return render_template('contact.html')
 

personalweb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{{ url_for('static', filename='styles/style_home.css') }}">

  <title>APP - {% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- bp is the blueprint -->
    <a class="navbar lead text-light" href="{{ url_for('bp.home') }}">
      <img class="img-fluid" src="{{ url_for('static', filename='img/nav-img.png') }}" alt="" width="100" height="60">
    </a>
    <a class="navbar lead text-light" href="{{ url_for('bp.home') }}">Home</a>
    <a class="navbar lead text-light" href="{{ url_for('project.show_projects') }}">Projects</a>
    <!-- <a class="navbar lead text-light" href="{{ url_for('bp.portfolio') }}">Portfolio</a> -->
    <a class="navbar lead text-light" href="{{ url_for('bp.contact') }}">Donations</a>
  </nav>

  {% for message in get_flashed_messages() %}
    <div class="container">
      <div class="container">
        <div class="container alert alert-info alert-dismissible mt-3" role="alert"> 
          <button type="button" class="close" data-dismiss="alert" >
            <span aria-hidden="true">&times</span>
          </button>
          {{ message }}
        </div>
      </div>
    </div>
  {% endfor %}

  {% block content %}
  {% endblock %}

  <footer class="page-footer bg-dark p-3 mb-0">
    <div class="navbar navbar-expand d-flex justify-content-center">
      <a class="navbar lead text-light" href="{{ url_for('bp.home') }}">
        <img class="img img-fluid" src="{{ url_for('static', filename='img/footer-img.png') }}" alt="" width="60" height="20">
      </a>
      <a class="narbar text-white small"><b>Mark Lacerenze </b></a>
      <span class="navbar text-light">|</span>
      <a class="navbar small text-light" href="https://github.com/mlacerenze">GitHub</a>
      <a class="navbar small text-light" href="https://www.linkedin.com/in/mlacerenze/">LinkedIn</a>
      <a class="navbar small text-light" href="https://www.instagram.com/mlacerenze/">Instagram</a>
      <a class="navbar small text-light" href="https://twitter.com/mlacerenze">Twitter</a>
    </div>
  </footer>
</body>
</html>

personalweb/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
  <div class="content">
    <img class="img img-fluid img-view" src="{{ url_for('static', filename='img/bg-contact.png') }}" style="width: 100%;">
    <div class="centered container">
      <h1 class="title">DID YOU LIKE THIS APP?</h1>
      <div class="container container-fluid">
        <p class="lead p-content">If you want to contribute, you can buy me a coffee or make a small donation to be able to continue uploading material</p>
      </div>
      <div class="container mt-5">
        <a class="text-secondary" href="https://cafecito.app/mlacerenze" target="blank">Cafecito(Argentina)</a>
        <span class="text-ligh">|</span>
        <a class="text-secondary" href="https://paypal.me/mlacerenze" target="blank">Paypal</a>
      </div>
    </div>
  </div>
{% endblock %}

personalweb/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="content">
    <img class="img img-fluid img-view" src="{{ url_for('static', filename='img/bg-img.png') }}" style="width: 100%;">
    <div class="centered container">
      <h1 class="title">WELCOME TODO LIST APP</h1>
      <div class="container">
        <p class="lead p-content">in this demo you will be able to add, edit and delete tasks that you want to do</p>
      </div>
    </div>
  </div>
{% endblock %}

personalweb/templates/portfolio.html
{% extends 'base.html' %}

{% block title %}Portfolio{% endblock %}

{% block content %}
  <div class="container">
    <p class="h2">Portfolio!</p>
  </div>
{% endblock %}

personalweb/templates/project/create.html
{% extends './base.html' %}

{% block title %}Create Project{% endblock %}

{% block content %}
<form action="{{ url_for('project.insert') }}" method="post">
  <div class="container form form-group">
    <h1 class="title mt-1">Create Project</h1>
    <div class="input-group mb-3">
      <span class="input-group-text bg-info" id="basic_addon1">Title</span>
      <input type="text" name="title" id="title" class="form-control" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text bg-info">Description</span>
      <textarea id="exampleFormControlTextarea1" class="form-control" name="description"></textarea>
    </div>
    <button type="submit" class="btn btn-success" value="Create">Create</button>
  </div>
  </form>
{% endblock %}

personalweb/templates/project/edit.html
{% extends './base.html' %}

{% block title %}Edit Project{% endblock %}

{% block content %}
  <form action="{{ url_for('project.update', id=project.id) }}" method="post">
    <div class="container form form-group">
      <p class="h2 mt-1">Edit Project</p>
      <div class="input-group mb-3">
        <span class="input-group-text bg-info" id="basic_addon1">Edit Title</span>
        <input type="text" name="title" id="title" class="form-control" aria-describedby="basic-addon1" value="{{project.title}}">
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text bg-info">Edit Description</span>
        <textarea id="exampleFormControlTextarea1" class="form-control" name="description">{{project.description}}"</textarea>
      </div>
      <button type="submit" class="btn btn-success" value="Save">Save</button>
    </div>
  </form>
{% endblock %}

personalweb/templates/project/index.html
{% extends './base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
  <div class="container">
    <div class="container mt-4 "> 
      <div class="container">
        <div class="container">
          <button class="btn btn-warning">
            <a href="{{ url_for('project.create') }}" class="text-light">New Project</a>
          </button>
        </div>
      </div>
    </div>
    
    <div class="content">
      <div class="container">
        <p class="h2 mt-1 title text-dark">My Tasks</p>
        
        <div class="container container-fluid mb-3">
          <ul class="list-group">
            {% if projects %}
              {% for project in projects %}
                <!-- Show taks -->
                <section class="container m-2">
                  <li class="list-group-item list-group-item-warning list-group-item-action"><h4>{{ project.title }}</h4></li>
                  <li class="list-group-item list-group-item-secondary"><p>{{ project.description }}</p></li> 
                  
                  <!-- Buttons to edit and delete -->
                  <div class="d-grip gap-2 d-md-flex justify-content-md-end mt-2">
                    <a href="{{ url_for('project.delete', id=project['id']) }}" class="text-light">
                      <button class="btn btn-danger">Delete</button>
                    </a>
                    <a href="{{ url_for('project.edit', id=project['id']) }}" class="text-light">
                      <button class="btn btn-info ml-2">Edit</button>
                    </a>
                  </div>
                </section>
              {% endfor %}
            {% else %}
            <section class="container m-2">
              <li class="list-group-item list-group-item-secondary text-center"><p>No task availables</p></li> 
            </section>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}